### PR TITLE
Initial commit, adding SVGs for repository.

### PR DESCRIPTION
**Pull request by hodgesto**
Adding first take of TOR and Browsing images.
Adding second take of all other images.

### CODE REVIEW

**Comment by hodgesto** [comment]
@michele-cldc Fork PR worked :smile: you can let me know either through here or through email about next steps or other questions. TOR images will be done very soon.

**Comment by mossy-nw** [comment]
great, looks good!  Seems like you just added the files to the pictures directory, and didn't get all in the .md files to replace the images.  That's fine by me to be light-touched on changes, I'll have a look over and drop in the images where they belong.  Nice work!  I'll comment here on specific images and if any changes seem urgent (i.e. for correctness).  Thanks again!

**Comment by hodgesto** [comment]
Yeah I wasn’t sure if you wanted me to put them in place or not, I’ll do that in the next commit, I just wanted to see if the PR would work like that. I had some questions about the TOR images that I’ll put in with the next commit as well.

**Comment by mossy-nw** [comment]
that's ok -- please let me put them in place, since the filenames are different.  Then you can send PRs   directly to the filenames for updated images.  Thanks!

**Pull request merged**
