### PR TITLE
Update hifi images to version 3

### PR DESCRIPTION
**Pull request by hodgesto**

### CODE REVIEW

**Comment by hodgesto** [comment]
Hi @michele-cldc @mossy-nw, I'm sending an email as we speak but I'm concerned that you don't want the fonts as-is right now at all. I updated them all to be a Libre font – Adobe Garamond Pro became Cormorant Garamond and Source Code Pro became Courier. If you'd like for me to switch out the serif with Liberation Sans, let me know before accepting this PR and I'll update it.

**Comment by mossy-nw** [comment]
hi toby -- the fonts  do look great, things have been super busy so I apologize for not being more in touch these last few months.  It looks like we're mostly set for the images we discussed, apart from GPG signing.  Are you still in your position to work on this?  If not, no worries, I can easily make one from the images you've already made.

**Comment by mossy-nw** [comment]
ah, unfortunately inkscape is not recognizing most (all?) of your fonts as text boxes, only as vector images.  Perhaps this is a problem with photoshop?  No need to troubleshoot (esp. if you are no longer in a paid position for this) but if you could share your original photoshop files I can sort this out.  thank you again for your great work on this!

**Comment by hodgesto** [comment]
Hi Michele @mossy-nw !
I've been _extremely_ busy moving, so I apologize for the delay, but yes I am still here at the Extended Campus. Yes they are all currently text outlines; I'll quickly send over the original files, but if you would like, I can make them all text boxes. Thanks much.

**Pull request merged**
